import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useWeb3Contract, useMoralis } from "react-moralis";
import { useEffect, useState } from "react";
import { abi, contractAddress } from "../constants/constants";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Logos from "../components/Logos";
import Socials from "../components/Socials";
import Footer from "../components/Footer";
import Simple from "../components/Simple";

export default function Home() {
  const { enableWeb3, isWeb3Enabled } = useMoralis();
  const [admin, setAdmin] = useState();

  const { runContractFunction: getAdmin } = useWeb3Contract({
    abi: abi,
    contractAddress: contractAddress,
    functionName: "getAdmin",
    params: {},
  });

  // useEffect(async()=> {
  //   let val = await getAdmin()
  //   setAdmin(val)
  // },[])

  const handleGet = async () => {
    let val = await getAdmin();
    // await setAdmin(val._hex)
    console.log(val);
  };
  return (
    <div className="bg-[#eee9e9] w-full" dir="rtl">
      <Head>
        <title>Neshar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Hero/>
      <Logos/>
      <Socials/>
      <Footer/>
      {/* <Simple/> */}
    </div>
  );
}
